# Generated by Django 4.0.1 on 2022-05-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_availble', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit_of_measure', models.CharField(choices=[('g', 'grams'), ('oz', 'ounces'), ('wh', 'whole units')], default='wh', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_name', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(blank=True, to='delites.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_sold', models.DateTimeField(auto_now_add=True)),
                ('sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('item_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delites.menu_item')),
            ],
            options={
                'ordering': ['-dt_sold'],
            },
        ),
        migrations.CreateModel(
            name='Recipe_Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delites.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delites.menu_item')),
            ],
        ),
    ]
